### ISSUE TITLE
How to Determin Width and Height of Text?

### ISSUE THREAD

**Issue by Dreded** [supermerill/Pyscad#7]
I am sure I am mising something Basic but say I make this command...

	text("Hello world!",45, "arial.ttf")

how would I know its width and Height?
I would like to create a name bade for example so I need to know where to put the surrounding rectangle

**Comment by supermerill** [comment]
It depends on the font... So there is no way to know before testing it.

**Comment by Dreded** [comment]
hmm thats unfortunate, was hoping to use it to create name badges quickly with 20mm on either side of name. cant do that I I dont know the size of the name.. guess I could make variables for each letter size.

**Comment by supermerill** [comment]
Ideally, the script should render the font in an image buffer, measure it and report the values.
But it's quite a bit of work. I don't know how to start in pure python
